"""Stable domain enumerations."""

from enum import StrEnum


class Action(StrEnum):
    """Trading action proposed by analysis or decision logic."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class AssetClass(StrEnum):
    """Asset classes supported by the initial domain."""

    METAL = "metal"
    FOREX = "forex"


class TradingMode(StrEnum):
    """Execution mode for a run or command."""

    BACKTEST = "backtest"
    PAPER = "paper"
    LIVE = "live"


class SignalReasonCode(StrEnum):
    """Stable, machine-readable evidence codes produced by Phase 2 strategies."""

    EMA_BULLISH_ALIGNMENT = "EMA_BULLISH_ALIGNMENT"
    EMA_BEARISH_ALIGNMENT = "EMA_BEARISH_ALIGNMENT"
    RSI_BULLISH_CONFIRMATION = "RSI_BULLISH_CONFIRMATION"
    RSI_BEARISH_CONFIRMATION = "RSI_BEARISH_CONFIRMATION"
    MACD_BULLISH_CONFIRMATION = "MACD_BULLISH_CONFIRMATION"
    MACD_BEARISH_CONFIRMATION = "MACD_BEARISH_CONFIRMATION"
    SUPPORT_REJECTION = "SUPPORT_REJECTION"
    RESISTANCE_REJECTION = "RESISTANCE_REJECTION"
    BULLISH_CANDLE_PATTERN = "BULLISH_CANDLE_PATTERN"
    BEARISH_CANDLE_PATTERN = "BEARISH_CANDLE_PATTERN"
    H1_BULLISH_CONTEXT = "H1_BULLISH_CONTEXT"
    H1_BEARISH_CONTEXT = "H1_BEARISH_CONTEXT"
    PULLBACK_TO_EMA21 = "PULLBACK_TO_EMA21"
    BULLISH_TRIGGER = "BULLISH_TRIGGER"
    BEARISH_TRIGGER = "BEARISH_TRIGGER"
    BREAKOUT_CONFIRMED = "BREAKOUT_CONFIRMED"
    BELOW_MINIMUM_CONFIDENCE = "BELOW_MINIMUM_CONFIDENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    CONFLICTING_SIGNALS = "CONFLICTING_SIGNALS"


class RiskRejectionCode(StrEnum):
    """Stable reason codes returned by the deterministic risk engine."""

    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    SYSTEM_NOT_READY = "SYSTEM_NOT_READY"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    BROKER_DISCONNECTED = "BROKER_DISCONNECTED"
    RISK_INPUT_INCOMPLETE = "RISK_INPUT_INCOMPLETE"
    STALE_DATA = "STALE_DATA"
    POSITION_NOT_RECONCILED = "POSITION_NOT_RECONCILED"
    DECISION_EXPIRED = "DECISION_EXPIRED"
    MARKET_CLOSED = "MARKET_CLOSED"
    SESSION_BLOCKED = "SESSION_BLOCKED"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    SLIPPAGE_RISK_HIGH = "SLIPPAGE_RISK_HIGH"
    NEWS_BLOCK = "NEWS_BLOCK"
    INVALID_STOP_LOSS = "INVALID_STOP_LOSS"
    STOP_DISTANCE_TOO_SMALL = "STOP_DISTANCE_TOO_SMALL"
    STOP_DISTANCE_TOO_LARGE = "STOP_DISTANCE_TOO_LARGE"
    LOW_REWARD_RISK = "LOW_REWARD_RISK"
    VOLUME_BELOW_MINIMUM = "VOLUME_BELOW_MINIMUM"
    INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN"
    TRADE_RISK_LIMIT = "TRADE_RISK_LIMIT"
    SYMBOL_RISK_LIMIT = "SYMBOL_RISK_LIMIT"
    STRATEGY_RISK_LIMIT = "STRATEGY_RISK_LIMIT"
    PORTFOLIO_RISK_LIMIT = "PORTFOLIO_RISK_LIMIT"
    CURRENCY_EXPOSURE_LIMIT = "CURRENCY_EXPOSURE_LIMIT"
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    DRAWDOWN_LIMIT = "DRAWDOWN_LIMIT"
    CONSECUTIVE_LOSS_COOLDOWN = "CONSECUTIVE_LOSS_COOLDOWN"
    POSITION_LIMIT = "POSITION_LIMIT"
    UNKNOWN_SYMBOL_SPEC = "UNKNOWN_SYMBOL_SPEC"
